spring:
  datasource:
      url: jdbc:mysql://localhost:3306/p_author?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root123
mybatis:
   mapperLocations: classpath:/mapper/*.xml
